name: themidnightwriter
favicon: null
layout_spectrum: 0.2527460802812129
typography_spectrum: 0.21709315478801727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8974201923701912
  lightness: 0.5277697613928467
  saturation: 0.9308128687553108
  rhythmicContrast: 0.6809748986270279
purpose: []
