color:
  brandStrength: 0.8974201923701912
  saturation: 0.9308128687553108
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.5277697613928467
  rhythmicContrast: 0.6809748986270279
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.2527460802812129
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: themidnightwriter
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2170931547880173
